@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Entity {
  # frames: List<Integer>
  # velocityX: double
  # height: double
  # width: double
  # velocityY: double
  # isMoving: boolean
  # level: Level
  # currentFrame: int
  # facingRight: boolean
  # coordinate: Coordinate
  + move(double, double): void
  # checkWallCollision(): void
  # checkEntityCollision(): void
  # handleEntityCollision(Entity): void
  # handlePacManEffect(): void
  # updateFrame(): void
  + stopFall(): void
  + update(): void
  # handleWallCollision(Wall): void
   coordinate: Coordinate
   velocityX: double
   velocityY: double
   die: boolean
   y: double
   x: double
   isMoving: boolean
   currentFrame: int
   frames: List<Integer>
   width: double
   info: List<String>
   level: Level
   frame: int
   facingRight: boolean
   height: double
}
class Observable {
  + notifyObservers(): void
  + notifyObservers(Object): void
  + deleteObserver(Observer): void
  + deleteObservers(): void
  # setChanged(): void
  + addObserver(Observer): void
  + countObservers(): int
  # clearChanged(): void
  + hasChanged(): boolean
}

Entity --|> Observable

@enduml
