@startuml

!theme plain
top to bottom direction
skinparam linetype ortho
'Split into 2 pages
page 4x4
skinparam pageMargin 10
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black

}

class Entity {
  # frames: List<Integer>
  # velocityX: double
  # height: double
  # width: double
  # velocityY: double
  # isMoving: boolean
  # level: Level
  # currentFrame: int
  # facingRight: boolean
  # coordinate: Coordinate
  + move(double, double): void
  # checkWallCollision(): void
  # checkEntityCollision(): void
  # handlePacManEffect(): void
  # updateFrame(): void
  + stopFall(): void
  + update(): void
  # {abstract}handleWallCollision(Wall): void
  # {abstract}handleEntityCollision(Entity): void
}
class Observable {
  + notifyObservers(): void
  + notifyObservers(Object): void
  + deleteObserver(Observer): void
  + deleteObservers(): void
  # setChanged(): void
  + addObserver(Observer): void
  + countObservers(): int
  # clearChanged(): void
  + hasChanged(): boolean
}



package PowerUpPackage {
    class PowerUp {
        - active: boolean
        - powerUpType: PowerUpType
        - powerUpStrategy: PowerUpStrategy
        # handleWallCollision(Wall): void
        + update(): void
        # handleEntityCollision(Entity): void
        - removePowerUp(): void
    }
    class PowerUpFactory {
        + createPowerUp(double, double, Level, PowerUpType): PowerUp
    }
    interface PowerUpStrategy {
        + applyPowerUp(Level): void
    }
    enum PowerUpType {
        + PowerUpType()
        + values(): PowerUpType[]
        + valueOf(String): PowerUpType
    }
    package PowerUpStrategyPackage {
        together {
            class AppleStrategy {
                + applyPowerUp(Level): void
            }
            class BlueGumStrategy {
                + applyPowerUp(Level): void
            }
            class BlueRingStrategy {
                + applyPowerUp(Level): void
            }
            class CherryStrategy {
                + applyPowerUp(Level): void
            }
            class ExtraLifeStrategy {
                + applyPowerUp(Level): void
            }
            class GlowingHeartStrategy {
                + applyPowerUp(Level): void
            }
            class GrapeStrategy {
                + applyPowerUp(Level): void
            }
            class PurpleGumStrategy {
                + applyPowerUp(Level): void
            }
            class PurpleRingStrategy {
                + applyPowerUp(Level): void
            }
            class RedCrossStrategy {
                + applyPowerUp(Level): void
            }
            class RedRIngStrategy {
                + applyPowerUp(Level): void
            }
            class SpeedShoesStrategy {
                + applyPowerUp(Level): void
            }
            class YellowGumStrategy {
                + applyPowerUp(Level): void
            }
        }

}

PowerUpFactory "<<create>>"..down> PowerUp
PowerUp *-down- PowerUpType :has
PowerUp *-left----- PowerUpStrategy :has
Entity -left-|> Observable : <<extends>>
Observable -[hidden]right> AppleStrategy
PowerUp "extends"-up--|>Entity
AppleStrategy .up.|> PowerUpStrategy
BlueGumStrategy .up.|> PowerUpStrategy
BlueRingStrategy ..up|> PowerUpStrategy
CherryStrategy .up.|> PowerUpStrategy
ExtraLifeStrategy .up.|> PowerUpStrategy
GlowingHeartStrategy .up.|> PowerUpStrategy
GrapeStrategy .up.|> PowerUpStrategy
PurpleGumStrategy .up.|> PowerUpStrategy
PurpleRingStrategy .up.|> PowerUpStrategy
RedCrossStrategy .up.|> PowerUpStrategy
RedRIngStrategy .up.|> PowerUpStrategy
SpeedShoesStrategy .up.|> PowerUpStrategy
YellowGumStrategy .up..|> PowerUpStrategy
AppleStrategy -[hidden]down> BlueGumStrategy
BlueGumStrategy -[hidden]down-> BlueRingStrategy
BlueRingStrategy -[hidden]down> CherryStrategy
CherryStrategy -[hidden]down-> ExtraLifeStrategy
ExtraLifeStrategy -[hidden]down> GlowingHeartStrategy
GlowingHeartStrategy -[hidden]down-> GrapeStrategy
GrapeStrategy -[hidden]down> PurpleGumStrategy
PurpleGumStrategy -[hidden]down-> PurpleRingStrategy
PurpleRingStrategy -[hidden]down> RedCrossStrategy
RedCrossStrategy -[hidden]down-> RedRIngStrategy
RedRIngStrategy -[hidden]down> SpeedShoesStrategy
SpeedShoesStrategy -[hidden]down> YellowGumStrategy
}



@enduml
